# Load additional configuration from env.properties if it exists (May not be present as file in all environments, e.g., for cloud development)
spring.config.import=optional:file:env.properties

# 1. Server Port
server.port=8080

# 2. Application Name
spring.application.name=url-shortener-api

# 3. Database-Configuration
spring.datasource.url=jdbc:h2:file:./data/${DB_DATABASE}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# 4. JPA / Hibernate Settings
# update-mode: creates tables if not exist, otherwise tries to alter tables to fit entities
spring.jpa.hibernate.ddl-auto=update
# false: deactivates the Open-Session-in-View pattern to avoid potential performance issues
spring.jpa.open-in-view=false

# 5. H2 Console (for development purposes)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 6. Custom Application Properties
app.baseurl=http://localhost
# Default Time-To-Live for shortened URLs in hours (0 = infinite)
app.defaultHoursTTL=0 
# Cleanup job cron expression
#   Cron-Syntax: Seconds Minutes Hours Day-of-Month Month Day-of-Week
#   "0 0 3 * * *" equals: daily at 3 AM
app.cleanup.cron=0 0 3 * * * 